Revert "Forbid clippy warnings"
This reverts commit c0942e12a3850d6d8e917dfd62662eb1ca8d6a3f.

1 | #![cfg_attr(feature = "cargo-clippy", deny(clippy::all))]
  |                                            ^^^^^^^^^^^
error[E0658]: scoped lint `clippy::all` is experimental (see issue #44690)